# Generated by Django 3.2.6 on 2021-08-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountID', models.CharField(max_length=20)),
                ('AccountAdminID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountAccMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountID', models.CharField(max_length=20)),
                ('AccountMemberID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountAdminID', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=255)),
                ('FirstName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AccountBillingAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountID', models.CharField(max_length=20)),
                ('BillingAccountID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountID', models.CharField(max_length=20)),
                ('CustomerID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('AccountMemberID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('AssociateID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractNumber', models.CharField(max_length=20)),
                ('PremiumCode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('BillingAccID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAccountInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillingAccountID', models.CharField(max_length=20)),
                ('InvoiceNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractNumber', models.CharField(max_length=20)),
                ('PlanName', models.CharField(max_length=255)),
                ('SeriesName', models.CharField(max_length=255)),
                ('LineOfBusiness', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContractBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractNumber', models.CharField(max_length=20)),
                ('PolicyCountContribution', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContractPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PremiumCode', models.CharField(max_length=20)),
                ('AnnualizePremium', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('CustomerID', models.CharField(max_length=20)),
                ('Alias', models.CharField(max_length=255)),
                ('RiskInformationURL', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAssociate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.CharField(max_length=20)),
                ('AssociateID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.CharField(max_length=20)),
                ('ContractNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.CharField(max_length=20)),
                ('RiskLevel', models.CharField(max_length=20)),
                ('CustomerID', models.CharField(max_length=20)),
                ('ContractNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerA', models.CharField(max_length=20)),
                ('CustomerB', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerA', models.CharField(max_length=20)),
                ('CustomerB', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNumber', models.CharField(max_length=20)),
                ('BAccName', models.CharField(max_length=255)),
                ('BillingAddress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SitCode', models.CharField(max_length=20)),
                ('AccountID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerAssociate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SitCode', models.CharField(max_length=20)),
                ('AssociateID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SitCode', models.CharField(max_length=20)),
                ('CompanyCode', models.CharField(max_length=20)),
                ('WritingNumber', models.CharField(max_length=20)),
                ('Level', models.CharField(max_length=255)),
                ('IssueDate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('AnnualizePremium', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=255)),
                ('ContractNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
